# /etc/NetworkManager/NetworkManager.conf
# CoLinux Desktop — NetworkManager configuration

[main]
plugins=keyfile

[ifupdown]
managed=true

[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.scan-rand-mac-address=yes
